### ISSUE TITLE
cloudscraper not in master

### ISSUE THREAD

**Issue by jee-r** [romancin/rutorrent-docker#33]
Hi Roman 

I have recently for now 2 or 3 day an error with the [cloudflare plugin](https://github.com/Novik/ruTorrent/wiki/Plugin_cloudflare)
```
 _cloudflare plugin: cloudscraper module can't be loaded in Python
```

 after a little investigation it seems that the python module [cloudscraper](https://github.com/VeNoMouS/cloudscraper) isn't installed in the [master branch](https://github.com/romancin/rutorrent-docker/blob/c07c514ce70c5dd11e328cca086db1eac8268dda/Dockerfile#L105) instead of the [dev branch](https://github.com/romancin/rutorrent-docker/blob/ec4e23b2bc3c4bed7fa3904ffa5872158c996507/Dockerfile#L108).

Is it just a forgetfulness or is there a technical reason ?

Thank You

**Comment by romancin** [comment]
Fixed on the current image.
