### ISSUE TITLE
Could not read resource file: ~/.rtorrent.rc

### ISSUE THREAD

**Issue by xyou365** [romancin/rutorrent-docker#54]
I have created one container from your cool docker image

> docker run -d --name=rutorrent \
-v ~/config:/config \
-v ~/downloads:/downloads \
-v ~/downloads/watch:/downloads/watch \
-v ~/downloads/completed:/downloads/completed \
-e PGID=0 -e PUID=0 -e TZ=Europe/Madrid \
-p 9443:443 \
-p 8080:80 \
-p 51415:51415 \
romancin/rutorrent:latest

But find I cannot open the https://IP:9443, then I ssh into the docker container `docker exec -it rutorrent /bin/sh`. Then run `rtorrent`. Then message `Could not read resource file: ~/.rtorrent.rc` shows up. 

Wondering that why it try to find the config file from `~` rather than from `/config/rtorrent/rtorrent.rc` (I know the .rc file is located in `/config/rtorrent/`).

**Comment by romancin** [comment]
It is not a good idea to use relative paths when mapping directories on docker containers. Please, try with absolute paths instead.
