### ISSUE TITLE
Bad response from server: (500 [error,initportcheck])

### ISSUE THREAD

**Issue by imjuzcy** [romancin/rutorrent-docker#80]
There seems to be an error checking if the port is open. I have port 51413 open but ruTorrent is not able to detect it. `Bad response from server: (500 [error,initportcheck])` appears in the log in the web interface.

**Comment by romancin** [comment]
> There seems to be an error checking if the port is open. I have port 51413 open but ruTorrent is not able to detect it. `Bad response from server: (500 [error,initportcheck])` appears in the log in the web interface.

Have you tried the latest image from yesterday? This problem should be solved on it.

**Comment by imjuzcy** [comment]
Yes, it works with the latest image!
